export const navLinks = [
    {
        id : 0,
        title : "Home",
        url : "/",
    },

    {
        id : 1,
        title : "Categories",
        url : "/categories",
    }, 

    {
        id : 2,
        title : "Products",
        url : "/Product",
    },
    
    {
        id : 3,
        title : "Contact",
        url : "/contact",
    },
];

export const Categorylist = [
    { id: 0, title: "Electronics", url: '/product'},
    { id: 1, title: "Jewelry", url: '/product'},
    { id: 2, title: "Men's Clothings", url: '/product'},
    { id: 3, title: "Women's Clothings", url: '/product'},
];

// export const Smile = smile;
// export const Cinderela = cinderela;
// export const Comedy = comedy;
// export const Right = right;
// export const natural = natural;
// export const Iconic = iconic;

import bcanva from '../assets/collections/bcanva.jpg';
import canvas from '../assets/collections/canvas.jpg';
import hat from '../assets/collections/hat.jpg';
import roundneck from '../assets/collections/roundneck.jpg';
import white from '../assets/collections/white.jpg';

export const sliderColections = [
    {
        id: 0,
        img: bcanva,
        text: 'Modern Bag',
    },
    {
        id: 1,
        img: canvas,
        text: 'Cute modern Canvas',
    },
    {
        id: 2,
        img: hat,
        text: 'Modern Hat',
    },
    {
        id: 3,
        img: roundneck,
        text: 'Beautiful roundneck',
    },
    {
        id: 4,
        img: white,
        text: 'Nice watch collection',
    },
];

export const storeData = [
    {
        id: 0,
        img: "",
        name: "Fashion Bag",
        text: "Female fashion bag",
        type: "Bags",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 1,
        img: "",
        name: "Fashion Bag",
        text: "Female fashion bag",
        type: "Bags",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 2,
        img: canvas,
        name: "Nice Shoe",
        text: "Normal hill shoe",
        type: "Shoes",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 3,
        img: canvas,
        name: "Nice Shoe",
        text: "Normal hill shoe",
        type: "Shoes",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 4,
        img: "",
        name: "Cute Suit",
        text: "Fashionist Suit",
        type: "Suits",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 5,
        img: "",
        name: "Cute Suit",
        text: "Fashionist Suit",
        type: "Suits",
        size: ['S', 'M', 'L', 'XL'],
        color: ['White', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 6,
        img: "",
        name: "Cool Jacket",
        text: "Fashionista Jacket",
        type: "Jackets",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 7,
        img: "",
        name: "Cool Jacket",
        text: "Fashionista Jacket",
        type: "Jackets",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 8,
        img: "",
        name: "Mens cute Jeans",
        text: "",
        type: "Jeans",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 9,
        img: "",
        name: "Mens cute Jeans",
        text: "",
        type: "Jeans",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 10,
        img: hat,
        name: "cute Hat",
        text: "Fashion hat",
        type: "Hat",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 11,
        img: hat,
        name: "cute Hat",
        text: "Fashion hat",
        type: "Hat",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Male",
        price: 20,
    },
    {
        id: 12,
        img: "",
        name: "Casual T-shirt",
        text: "Normal and cute T-shirt",
        type: "T-shirt",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 13,
        img: "",
        name: "Casual T-shirt",
        text: "Normal and cute T-shirt",
        type: "T-shirt",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 14,
        img: "",
        name: "Casual roundneck",
        text: "Casual roundneck top",
        type: "Roundneck",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 15,
        img: "",
        name: "Casual roundneck",
        text: "Casual roundneck top",
        type: "Roundneck",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 16,
        img: "",
        name: "Casual roundneck",
        text: "Casual roundneck top",
        type: "Roundneck",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 17,
        img: "",
        name: "Fashion Bag",
        text: "Female fashion bag",
        type: "Bags",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 18,
        img: canvas,
        name: "Nice Shoe",
        text: "Normal hill shoe",
        type: "Shoes",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 19,
        img: "",
        name: "Cute Suit",
        text: "Fashionist Suit",
        type: "Suits",
        size: ['S', 'M', 'L', 'XL'],
        color: ['Grey', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 20,
        img: hat,
        name: "cute Hat",
        text: "Fashion hat",
        type: "Hat",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Male",
        price: 20,
    },
    {
        id: 21,
        img: "",
        name: "Casual T-shirt",
        text: "Normal and cute T-shirt",
        type: "T-shirt",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'red', 'green'],
        gender: "Female",
        price: 20,
    },
    {
        id: 22,
        img: "",
        name: "Mens cute Jeans",
        text: "",
        type: "Jeans",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
    {
        id: 23,
        img: "",
        name: "Cool Jacket",
        text: "Fashionista Jacket",
        type: "Jackets",
        size: ['S', 'M', 'L', 'XL'],
        color: ['black', 'blue'],
        gender: "Male",
        price: 20,
    },
];